# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-uIJdYjDDNh0MOSRLlTGVuPResIU__2o
"""

import os
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

import joblib

data = pd.read_csv("iris.csv")

X = data.drop['species']
y = data['species']

model = DecisionTreeClassifier(max_depth=3, random_state=42)

model.fit(X,y)

joblib.dump(model, 'model.joblib')

pirnt("Done!!")